language: cpp
compiler: gcc
matrix:
    include:
        - os: linux
          env: TARGET_OS=linux
        - os: linux
          env: TARGET_OS=win32
        - os: linux
          env: TARGET_OS=win64
        - os: osx
before_install:
    - if [ $TRAVIS_OS_NAME == linux ]; then
          if [ $TARGET_OS != linux ]; then sudo add-apt-repository ppa:tobydox/mingw -y; fi
          if [ $TARGET_OS == linux ]; then sudo add-apt-repository ppa:kalakris/cmake -y; fi
          sudo apt-get update -qq;
      fi
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
install:
    - if [ $TRAVIS_OS_NAME == linux ]; then
          if [ $TARGET_OS == linux ]; then
              sudo apt-get install -y cmake libqt4-dev libsndfile-dev fftw3-dev libvorbis-dev libogg-dev libasound2-dev libjack-dev libsdl-dev libsamplerate0-dev libstk0-dev libfluidsynth-dev portaudio19-dev wine-dev g++-multilib libfltk1.3-dev libgig-dev;
          fi
          if [ $TARGET_OS != linux ]; then sudo apt-get install -y nsis cloog-isl libmpc2 mingw32; fi
          if [ $TARGET_OS != linux ]; then sudo apt-get install -y mingw32-x-qt mingw32-x-sdl mingw32-x-libvorbis mingw32-x-fluidsynth mingw32-x-stk mingw32-x-glib2 mingw32-x-portaudio mingw32-x-libsndfile mingw32-x-fftw mingw32-x-flac mingw32-x-fltk mingw32-x-libsamplerate mingw32-x-pkgconfig mingw32-x-binutils mingw32-x-gcc mingw32-x-runtime mingw32-x-libgig; fi
          if [ $TARGET_OS == win64 ]; then sudo apt-get install -y mingw64-x-qt mingw64-x-sdl mingw64-x-libvorbis mingw64-x-fluidsynth mingw64-x-stk mingw64-x-glib2 mingw64-x-portaudio mingw64-x-libsndfile mingw64-x-fftw mingw64-x-flac mingw64-x-fltk mingw64-x-libsamplerate mingw64-x-pkgconfig mingw64-x-binutils mingw64-x-gcc mingw64-x-runtime mingw64-x-libgig; fi;
      fi
    - if [ $TRAVIS_OS_NAME == osx ]; then
          brew upgrade qt libsndfile fftw libvorbis libogg jack sdl libsamplerate stk fluid-synth portaudio fltk
      fi
before_script:
    - mkdir build && cd build
script:
    - if [ $TRAVIS_OS_NAME == linux ]; then
          if [ $TARGET_OS == win32 ]; then ../build_mingw32 || ../build_mingw32; fi
          if [ $TARGET_OS == win64 ]; then ../build_mingw64 || ../build_mingw64; fi
          if [ $TARGET_OS == linux ]; then cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..; fi
      fi
    - if [ $TRAVIS_OS_NAME == osx ]; then
          cmake ..
      fi
    - make -j4 VERBOSE=1
    - if [ $TARGET_OS == linux ]; then make tests && ./tests/tests; fi;
before_deploy: make package
deploy:
    provider: releases
    api_key:
        secure: d4a+x4Gugpss7JK2DcHjyBZDmEFFh4iVfKDfITSD50T6Mc6At4LMgojvEu+6qT6IyOY2vm3UVT6fhyeuWDTRDwW9tfFlaHVA0h8aTRD+eAXOA7pQ8rEMwQO3+WCKuKTfEqUkpL4wxhww8dpkv54tqeIs0S4TBqz9tk8UhzU7XbE=
    file: lmms-${TRAVIS_TAG:1}-$TARGET_OS.exe
    on:
        tags: true
        all_branches: true
        condition: "$TARGET_OS != linux"
    repo: LMMS/lmms
